language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

install: travis_retry composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit --verbose
